Repository RAF-SI-2022/Bolnica-1-Frontend, pull requests merged in 2023-06, with the labels that each got.

#208 Stacionar
  .prow/postsubmits.yaml
  kubernetes-front/frontend-deployment.yaml
  kubernetes-front/ingress.yaml
Labels: size/L

#210 kovid servis izmena na params
  src/app/services/covid-service/covid-service.service.ts
Labels: size/S

#221 kubernetes
  .prow/postsubmits.yaml
  kubernetes-front/b-1-frontend-chart/.helmignore
  kubernetes-front/b-1-frontend-chart/Chart.yaml
  kubernetes-front/b-1-frontend-chart/templates/NOTES.txt
  kubernetes-front/b-1-frontend-chart/templates/_helpers.tpl
  kubernetes-front/b-1-frontend-chart/templates/deployment.yaml
  kubernetes-front/b-1-frontend-chart/templates/ingress.yaml
  kubernetes-front/b-1-frontend-chart/templates/service.yaml
  kubernetes-front/b-1-frontend-chart/templates/tests/test-connection.yaml
  kubernetes-front/b-1-frontend-chart/values.yaml
Labels: size/L

#223 Izmena u postsubmits.yaml
  .prow/postsubmits.yaml
Labels: size/XS

#233 reset forme doktor
  src/app/components/doctor/covid/doctor-covid-create-referral/doctor-covid-create-referral.component.ts
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/components/doctor/doctor-infirmary-create-referral/doctor-infirmary-create-referral.component.ts
  src/app/components/doctor/doctor-infirmary-discharge-list/doctor-infirmary-discharge-list.component.ts
  src/environments/environment.ts
Labels: size/L

#234 Sredjeno je cuvanje forme
  src/app/components/admin/admin-add-employee/admin-add-employee.component.ts
  src/app/components/nurse/nurse-add-patient/nurse-add-patient.component.ts
  src/app/components/nurse/nurse-infirmary-patient-admission/nurse-infirmary-patient-admission.component.html
  src/app/components/nurse/nurse-infirmary-patient-admission/nurse-infirmary-patient-admission.component.ts
  src/app/components/nurse/nurse-infirmary-register-state/nurse-infirmary-register-state.component.ts
  src/app/components/nurse/nurse-infirmary-register-visit/nurse-infirmary-register-visit.component.ts
  src/app/components/nurse/nurse-infirmary-schedule-admission/nurse-infirmary-schedule-admission.component.ts
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.ts
Labels: size/L

#236 Resetovanje polja za create referral tip stranice
  src/app/components/doctor/covid/doctor-covid-create-referral/doctor-covid-create-referral.component.ts
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/components/doctor/doctor-infirmary-create-referral/doctor-infirmary-create-referral.component.ts
Labels: size/M

#239 Kubernetes izmene
  .prow/postsubmits.yaml
  kubernetes-front/b-1-frontend-chart/templates/deployment.yaml
  kubernetes-front/b-1-frontend-chart/templates/ingress.yaml
  kubernetes-front/b-1-frontend-chart/values.yaml
Labels: size/S

#237 radni nalozi biohemicar
  src/app/components/biochemist/biochemist-search-work-orders/biochemist-search-work-orders.component.html
  src/app/components/biochemist/biochemist-search-work-orders/biochemist-search-work-orders.component.ts
  src/app/components/doctor/doctor-infirmary-medical-chart/doctor-infirmary-medical-chart.component.html
  src/app/components/doctor/doctor-infirmary-medical-chart/doctor-infirmary-medical-chart.component.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.ts
Labels: size/S

#238 Izmenjene stvari sa "?" :)
  src/app/components/biochemist/biochemist-search-work-orders/biochemist-search-work-orders.component.css
  src/app/components/doctor/covid/doctor-covid-create-referral/doctor-covid-create-referral.component.css
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.css
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.html
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/components/doctor/doctor-infirmary-create-referral/doctor-infirmary-create-referral.component.html
  src/app/components/doctor/doctor-infirmary-create-referral/doctor-infirmary-create-referral.component.ts
  src/app/components/doctor/doctor-infirmary-discharge-list/doctor-infirmary-discharge-list.component.html
  src/app/components/doctor/doctor-infirmary-discharge-list/doctor-infirmary-discharge-list.component.ts
  src/app/components/doctor/doctor-infirmary-medical-chart/doctor-infirmary-medical-chart.component.html
  src/app/components/doctor/doctor-infirmary-medical-chart/doctor-infirmary-medical-chart.component.ts
  src/app/components/doctor/doctor-infirmary-medical-record/doctor-infirmary-medical-record.component.html
  src/app/components/doctor/doctor-infirmary-medical-record/doctor-infirmary-medical-record.component.ts
  src/app/components/doctor/doctor-infirmary-state-history/doctor-infirmary-state-history.component.html
  src/app/components/doctor/doctor-infirmary-state-history/doctor-infirmary-state-history.component.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.css
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/doctor/doctor-patients-infirmary/doctor-patients-infirmary.component.css
  src/app/components/doctor/doctor-schedule-exam/doctor-schedule-exam.component.html
  src/app/components/doctor/doctor-schedule-exam/doctor-schedule-exam.component.ts
  src/app/components/nurse/covid/nurse-covid-ambulance/nurse-covid-ambulance.component.css
  src/app/components/nurse/covid/nurse-covid-ambulance/nurse-covid-ambulance.component.html
  src/app/components/nurse/covid/nurse-covid-ambulance/nurse-covid-ambulance.component.ts
  src/app/components/nurse/nurse-infirmary-patient-admission/nurse-infirmary-patient-admission.component.css
  src/app/components/nurse/nurse-infirmary-schedule-admission/nurse-infirmary-schedule-admission.component.css
  src/app/components/nurse/nurse-infirmary-scheduled-patients/nurse-infirmary-scheduled-patients.component.css
  src/app/components/nurse/nurse-infirmary-search-admission/nurse-infirmary-search-admission.component.css
  src/app/components/nurse/nurse-infirmary-workspace/nurse-infirmary-workspace.component.css
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.css
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.html
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.ts
  src/app/components/technician/technician-issuing-results/technician-issuing-results.component.css
  src/app/components/technician/technician-patient-admission/technician-patient-admission.component.css
Labels: size/L

#240 Kubernetes ispravka
  kubernetes-front/b-1-frontend-chart/templates/deployment.yaml
Labels: size/XS

#241 Kovid statistika dodata
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/doctor/covid/doctor-covid-statistics/doctor-covid-statistics.component.css
  src/app/components/doctor/covid/doctor-covid-statistics/doctor-covid-statistics.component.html
  src/app/components/doctor/covid/doctor-covid-statistics/doctor-covid-statistics.component.ts
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.css
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.html
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.ts
  src/app/components/nurse/covid/nurse-covid-statistics/nurse-covid-statistics.component.css
  src/app/components/nurse/covid/nurse-covid-statistics/nurse-covid-statistics.component.html
  src/app/components/nurse/covid/nurse-covid-statistics/nurse-covid-statistics.component.ts
  src/app/models/laboratory/Prescription.ts
Labels: size/XXL

#243 Sredjeno clearovanje fieldova
  src/app/components/doctor/covid/doctor-covid-create-referral/doctor-covid-create-referral.component.ts
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.html
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/components/nurse/nurse-infirmary-patient-admission/nurse-infirmary-patient-admission.component.ts
  src/app/components/nurse/nurse-infirmary-scheduled-patients/nurse-infirmary-scheduled-patients.component.ts
Labels: size/S

#245 Cuvanje forme
  src/app/components/doctor/covid/doctor-covid-exam/doctor-covid-exam.component.ts
  src/app/components/nurse/covid/nurse-covid-ambulance/nurse-covid-ambulance.component.ts
Labels: size/M

#249 cypress test
  cypress/e2e/covid.cy.ts
  src/app/components/doctor/covid/doctor-covid-exam/doctor-covid-exam.component.html
  src/app/components/doctor/covid/doctor-covid-exam/doctor-covid-exam.component.ts
  src/app/components/nurse/covid/nurse-covid-ambulance/nurse-covid-ambulance.component.html
  src/app/components/nurse/covid/nurse-covid-ambulance/nurse-covid-ambulance.component.ts
Labels: size/M
