Repository RAF-SI-2022/Bolnica-1-Frontend, pull requests merged in 2023-04, with the labels that each got.

#83 Kalendar dorada
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/nurse/nurse-schedule-appointment/nurse-schedule-appointment.component.html
  src/app/components/nurse/nurse-schedule-appointment/nurse-schedule-appointment.component.ts
Labels: size/L

#84 Doradjen doctor-medical-chart, uradjena technician-schedule-lab-examination komponenta
  src/app/app/app.component.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/general/login/login.component.ts
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.html
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.ts
  src/app/services/laboratory-service/laboratory.service.ts
  src/app/services/patient-service/patient.service.ts
Labels: size/XL

#85 doctor workspace one patient komponenta izmene
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.html
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.ts
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.html
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
  src/app/components/nurse/nurse-schedule-appointment/nurse-schedule-appointment.component.ts
  src/app/models/patient/Anamnesis.ts
  src/app/models/patient/DiagnosisCode.ts
  src/app/models/patient/ExaminationHistoryCreate.ts
  src/app/models/patient/MedicalHistoryCreateDto.ts
  src/app/services/patient-service/patient.service.ts
Labels: size/L

#86 Refactor & Cleanup Part 1
  src/app/app/app.component.ts
  src/app/components/admin/admin-add-employee/admin-add-employee.component.ts
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.html
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.ts
  src/app/components/admin/admin-search-employee/admin-search-employee.component.html
  src/app/components/admin/admin-search-employee/admin-search-employee.component.ts
  src/app/components/admin/admin-workspace/admin-workspace.component.html
  src/app/components/admin/admin-workspace/admin-workspace.component.ts
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.html
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.ts
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.ts
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
  src/app/components/general/login/login.component.ts
  src/app/components/general/new-password/new-password.component.ts
  src/app/components/general/profile/profile.component.html
  src/app/components/general/profile/profile.component.ts
  src/app/components/nurse/nurse-edit-patient/nurse-edit-patient.component.ts
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.ts
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.ts
  src/app/models/Message.ts
  src/app/models/models.ts
  src/app/services/auth.service.ts
  src/app/services/laboratory-service/laboratory.service.ts
  src/app/services/patient-service/patient.service.ts
  src/app/services/user-service/user.service.ts
Labels: size/XXL

#87 Izmena 58: radni prostor za kreiranje uputa
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.html
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
Labels: size/L

#88 Dodate permisije i ispravljena paginacija kod doctor-search-patients i nurse-search-patients, sredjen prikaz za delete
  src/app/components/admin/admin-add-employee/admin-add-employee.component.html
  src/app/components/admin/admin-add-employee/admin-add-employee.component.ts
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.html
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.ts
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.html
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.ts
  src/app/components/general/profile/profile.component.html
  src/app/components/general/profile/profile.component.ts
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.html
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.ts
  src/app/models/models.ts
Labels: size/L

#89 Sredjene vakcine i alergije, sredjen bag u nurse-edit-patient
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/nurse/nurse-edit-patient/nurse-edit-patient.component.html
  src/app/components/nurse/nurse-edit-patient/nurse-edit-patient.component.ts
  src/app/models/patient-enums/VaccinationType.ts
  src/app/models/patient/GeneralMedicalDataCreate.ts
  src/app/models/patient/Vaccination.ts
  src/app/services/patient-service/patient.service.ts
Labels: size/L

#90 kreiranje pregleda
  src/app/components/nurse/nurse-edit-patient/nurse-edit-patient.component.html
  src/app/components/nurse/nurse-schedule-appointment/nurse-schedule-appointment.component.html
  src/app/components/nurse/nurse-schedule-appointment/nurse-schedule-appointment.component.ts
Labels: size/L

#93 izmene u doctor workspace one patient, izdavanje izvrsenih lab analiza i kreiranje uputa
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.html
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.html
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.ts
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
  src/app/components/technician/technician-issuing-results/technician-issuing-results.component.html
  src/app/components/technician/technician-issuing-results/technician-issuing-results.component.ts
  src/app/models/laboratory/PrescriptionCreate.ts
  src/app/models/patient/MedicalHistoryCreateDto.ts
  src/app/services/laboratory-service/laboratory.service.ts
  src/app/services/patient-service/patient.service.ts
Labels: size/L

#95 Dodat klik na red u doctor-workspace i ispravljeni nazivi alergija
  src/app/app-routing.module.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.html
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.html
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
Labels: size/M

#98 Ispravka doctor workspace one
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.html
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.ts
  src/app/services/patient-service/patient.service.ts
Labels: size/M

#99 Sladje objekta u technician-issuing-results-details
  src/app/app-routing.module.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.ts
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.html
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
  src/app/components/nurse/nurse-add-patient/nurse-add-patient.component.ts
  src/app/components/technician/technician-issuing-results-details/technician-issuing-results-details.component.ts
  src/app/components/technician/technician-issuing-results/technician-issuing-results.component.html
  src/app/components/technician/technician-issuing-results/technician-issuing-results.component.ts
Labels: size/M

#100 Dopuna za prosledjivanje objekta
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.ts
  src/app/components/technician/technician-issuing-results-details/technician-issuing-results-details.component.ts
  src/app/models/laboratory/LabWorkOrder.ts
  src/app/models/laboratory/Prescription.ts
Labels: size/M

#101 Sredjene vakcine i alergije
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/models/patient/VaccinationDataDto.ts
  src/app/services/patient-service/patient.service.ts
Labels: size/M

#102 dodati podaci o pacijentu u workspace one patient
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.html
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.ts
Labels: size/M

#103 Dopuna komponenti
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.ts
  src/app/components/technician/technician-issuing-results-details/technician-issuing-results-details.component.ts
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.html
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.ts
  src/app/services/laboratory-service/laboratory.service.ts
  src/app/services/patient-service/patient.service.ts
Labels: size/L

#105 Sprint 2
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
  src/app/components/nurse/nurse-workspace/nurse-workspace.component.html
  src/app/components/nurse/nurse-workspace/nurse-workspace.component.ts
  src/app/models/patient/ExamForPatient.ts
  src/app/services/examination-service/examination.service.ts
Labels: size/XL

#107 Dopuna komponenti
  src/app/app-routing.module.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.ts
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.html
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.ts
  src/app/services/laboratory-service/laboratory.service.ts
  src/app/services/patient-service/patient.service.ts
Labels: size/L

#108 Update status
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
  src/app/components/nurse/nurse-workspace/nurse-workspace.component.html
  src/app/components/nurse/nurse-workspace/nurse-workspace.component.ts
  src/app/services/examination-service/examination.service.ts
Labels: size/M

#110 uput
  src/app/app-routing.module.ts
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.html
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.html
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.ts
  src/app/models/laboratory/LabAnalysisDto.ts
  src/app/models/laboratory/ParameterDto.ts
  src/app/models/laboratory/PrescriptionAnalysis.ts
  src/app/services/laboratory-service/laboratory.service.ts
  src/app/services/patient-service/patient.service.ts
Labels: size/L

#109 Dodati testovi za nurse i doctor
  cypress/e2e/admin.cy.ts
  cypress/e2e/doctor.cy.ts
  cypress/e2e/login.cy.ts
  cypress/e2e/nurse.cy.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  src/app/components/nurse/nurse-add-patient/nurse-add-patient.component.html
Labels: size/L

#113 Dodate komponente za issue #111 i sredjene sitnice
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/app/app.component.html
  src/app/components/biochemist/biochemist-daily-work-orders/biochemist-daily-work-orders.component.css
  src/app/components/biochemist/biochemist-daily-work-orders/biochemist-daily-work-orders.component.html
  src/app/components/biochemist/biochemist-daily-work-orders/biochemist-daily-work-orders.component.spec.ts
  src/app/components/biochemist/biochemist-daily-work-orders/biochemist-daily-work-orders.component.ts
  src/app/components/biochemist/biochemist-details-analysis/biochemist-details-analysis.component.css
  src/app/components/biochemist/biochemist-details-analysis/biochemist-details-analysis.component.html
  src/app/components/biochemist/biochemist-details-analysis/biochemist-details-analysis.component.spec.ts
  src/app/components/biochemist/biochemist-details-analysis/biochemist-details-analysis.component.ts
  src/app/components/biochemist/biochemist-search-work-orders/biochemist-search-work-orders.component.css
  src/app/components/biochemist/biochemist-search-work-orders/biochemist-search-work-orders.component.html
  src/app/components/biochemist/biochemist-search-work-orders/biochemist-search-work-orders.component.spec.ts
  src/app/components/biochemist/biochemist-search-work-orders/biochemist-search-work-orders.component.ts
  src/app/components/biochemist/biochemist-search/biochemist-search.component.html
  src/app/components/biochemist/biochemist-search/biochemist-search.component.spec.ts
  src/app/components/biochemist/biochemist-search/biochemist-search.component.ts
  src/app/components/general/login/login.component.ts
  src/app/components/technician/technician-patient-admission/technician-patient-admission.component.html
Labels: size/XL

#116 Uradjena komponenta technician-patient-admission
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/technician/technician-patient-admission/technician-patient-admission.component.html
  src/app/components/technician/technician-patient-admission/technician-patient-admission.component.ts
  src/app/services/laboratory-service/laboratory.service.ts
Labels: size/L

#118 Dodate work order metode
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/services/laboratory-service/laboratory.service.ts
  src/app/services/patient-service/patient.service.ts
Labels: size/M

#119 Doradjen doctor-medical-chart
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/models/laboratory/LabAnalysis.ts
  src/app/models/laboratory/LabWorkOrderWithAnalysis.ts
  src/app/models/laboratory/Parameter.ts
  src/app/models/laboratory/ParameterAnalysisResultWithDetails.ts
  src/app/services/laboratory-service/laboratory.service.ts
Labels: size/L

#120 Doradjena komponenta technician-schedule-lab-examination
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/general/login/login.component.ts
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.html
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.ts
  src/app/services/laboratory-service/laboratory.service.ts
Labels: size/L

#121 Docker-Frontend
  Dockerfile
  docker-compose.yml
Labels: size/M

#123 Sredjena paginacija na doctor-medical-chart i jos neke komponente
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/technician/technician-patient-admission/technician-patient-admission.component.ts
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.ts
  src/app/services/laboratory-service/laboratory.service.ts
  src/app/services/prescription-service/prescription-service.service.ts
Labels: size/XL

#124 Sprint 3
  src/app/app.module.ts
Labels: size/XS

#126 Doctor-medical-chart doradjen
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.html
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.ts
  src/app/models/patient/ExaminationHistory.ts
  src/app/models/prescription/PrescriptionDoneDto.ts
  src/app/services/laboratory-service/laboratory.service.ts
  src/app/services/prescription-service/prescription-service.service.ts
Labels: size/L

#127 pregledi izmene
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.html
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.html
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
  src/app/components/nurse/nurse-schedule-appointment-new/nurse-schedule-appointment-new.component.css
  src/app/components/nurse/nurse-schedule-appointment-new/nurse-schedule-appointment-new.component.html
  src/app/components/nurse/nurse-schedule-appointment-new/nurse-schedule-appointment-new.component.spec.ts
  src/app/components/nurse/nurse-schedule-appointment-new/nurse-schedule-appointment-new.component.ts
  src/app/components/nurse/nurse-schedule-appointment/nurse-schedule-appointment.component.ts
  src/app/components/nurse/nurse-workspace/nurse-workspace.component.html
  src/app/components/nurse/nurse-workspace/nurse-workspace.component.ts
Labels: size/L

#128 uputi
  src/app/app/app.component.html
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.html
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
  src/app/models/models.ts
  src/app/services/user-service/user.service.ts
Labels: size/L

#129 issue 55 i 111
  src/app/components/biochemist/biochemist-daily-work-orders/biochemist-daily-work-orders.component.html
  src/app/components/biochemist/biochemist-daily-work-orders/biochemist-daily-work-orders.component.ts
  src/app/components/biochemist/biochemist-details-analysis/biochemist-details-analysis.component.html
  src/app/components/biochemist/biochemist-details-analysis/biochemist-details-analysis.component.ts
  src/app/components/biochemist/biochemist-search-work-orders/biochemist-search-work-orders.component.html
  src/app/components/biochemist/biochemist-search-work-orders/biochemist-search-work-orders.component.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/technician/technician-issuing-results/technician-issuing-results.component.html
  src/app/components/technician/technician-issuing-results/technician-issuing-results.component.ts
  src/app/models/laboratory/LabWorkOrder.ts
  src/app/services/laboratory-service/laboratory.service.ts
Labels: size/L

#130 Doradjene komponente technician-patient-admission i technician-schedule-lab-examination
  src/app/components/technician/technician-patient-admission/technician-patient-admission.component.html
  src/app/components/technician/technician-patient-admission/technician-patient-admission.component.ts
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.html
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.ts
  src/app/models/laboratory-enums/ExaminationStatus.ts
  src/app/services/laboratory-service/laboratory.service.ts
Labels: size/L

#133 izmene za prikaz detalja
  src/app/components/biochemist/biochemist-daily-work-orders/biochemist-daily-work-orders.component.html
  src/app/components/biochemist/biochemist-daily-work-orders/biochemist-daily-work-orders.component.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/models/laboratory/LabWorkOrderNew.ts
  src/app/services/laboratory-service/laboratory.service.ts
Labels: size/L

#135 Izmenjene rute i dodata validacija
  src/app/components/admin/admin-add-employee/admin-add-employee.component.ts
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.html
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/components/technician/technician-patient-admission/technician-patient-admission.component.html
  src/app/components/technician/technician-patient-admission/technician-patient-admission.component.ts
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.html
  src/app/components/technician/technician-schedule-lab-examination/technician-schedule-lab-examination.component.ts
  src/app/services/laboratory-service/laboratory.service.ts
Labels: size/L

#138 Izmenjene dijagnoze
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.html
Labels: size/XS

#140 gotovo
  src/app/components/biochemist/biochemist-details-analysis/biochemist-details-analysis.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/services/prescription-service/prescription-service.service.ts
Labels: size/M

#142 Docker - Harbor
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
Labels: size/L

#143 Sprint 3
  src/app/components/biochemist/biochemist-details-analysis/biochemist-details-analysis.component.ts
Labels: size/XS
