Repository RAF-SI-2022/Bolnica-1-Frontend, pull requests merged in 2023-05, with the labels that each got.

#161 Dopunjene komponente doctor-infirmary-medical-chart i doctor-create-referral
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.html
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/components/doctor/doctor-infirmary-medical-chart/doctor-infirmary-medical-chart.component.html
  src/app/components/doctor/doctor-infirmary-medical-chart/doctor-infirmary-medical-chart.component.ts
  src/app/components/doctor/doctor-infirmary-workspace/doctor-infirmary-workspace.component.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/services/infirmary-service/infirmary.service.ts
Labels: size/L

#162 Sprint 3
  .dockerignore
Labels: size/XS

#167 Stacionar
  src/app/components/doctor/doctor-infirmary-create-referral/doctor-infirmary-create-referral.component.ts
  src/app/components/nurse/nurse-schedule-appointment/nurse-schedule-appointment.component.ts
Labels: size/M

#168 Sredjena paginacija
  src/app/components/doctor/doctor-infirmary-create-referral/doctor-infirmary-create-referral.component.ts
  src/app/components/doctor/doctor-infirmary-state-history/doctor-infirmary-state-history.component.ts
  src/app/components/doctor/doctor-patients-infirmary/doctor-patients-infirmary.component.ts
  src/app/components/nurse/nurse-infirmary-patient-admission/nurse-infirmary-patient-admission.component.ts
  src/app/components/nurse/nurse-infirmary-schedule-admission/nurse-infirmary-schedule-admission.component.ts
  src/app/components/nurse/nurse-infirmary-scheduled-patients/nurse-infirmary-scheduled-patients.component.ts
  src/app/components/nurse/nurse-infirmary-search-admission/nurse-infirmary-search-admission.component.ts
  src/app/components/nurse/nurse-infirmary-state-history/nurse-infirmary-state-history.component.ts
  src/app/components/nurse/nurse-infirmary-visits-history/nurse-infirmary-visits-history.component.ts
  src/app/components/nurse/nurse-infirmary-workspace/nurse-infirmary-workspace.component.ts
Labels: size/M

#195 css
  cypress/e2e/infirmary.cy.ts
  src/app/components/nurse/nurse-infirmary-workspace/nurse-infirmary-workspace.component.css
Labels: size/L

#197 izmena
  src/app/services/examination-service/examination.service.ts
Labels: size/XS

#199 rute ingres
  src/environments/environment.ts
Labels: size/XS

#206 Finished: #203
  src/app/components/doctor/covid/doctor-covid-create-referral/doctor-covid-create-referral.component.css
  src/app/components/doctor/covid/doctor-covid-create-referral/doctor-covid-create-referral.component.html
  src/app/components/doctor/covid/doctor-covid-create-referral/doctor-covid-create-referral.component.ts
Labels: size/XL

#207 Finished #200
  src/app/components/doctor/covid/doctor-covid-exam/doctor-covid-exam.component.css
  src/app/components/doctor/covid/doctor-covid-exam/doctor-covid-exam.component.html
  src/app/components/doctor/covid/doctor-covid-exam/doctor-covid-exam.component.ts
  src/app/components/doctor/covid/doctor-covid-statistics/doctor-covid-statistics.component.css
  src/app/components/doctor/covid/doctor-covid-statistics/doctor-covid-statistics.component.html
  src/app/components/doctor/covid/doctor-covid-statistics/doctor-covid-statistics.component.ts
  src/app/components/doctor/covid/doctor-covid-waiting-room/doctor-covid-waiting-room.component.css
  src/app/components/doctor/covid/doctor-covid-waiting-room/doctor-covid-waiting-room.component.html
  src/app/components/nurse/covid/nurse-covid-ambulance/nurse-covid-ambulance.component.css
  src/app/components/nurse/covid/nurse-covid-ambulance/nurse-covid-ambulance.component.html
  src/app/components/nurse/covid/nurse-covid-ambulance/nurse-covid-ambulance.component.ts
  src/app/components/nurse/covid/nurse-covid-statistics/nurse-covid-statistics.component.css
  src/app/components/nurse/covid/nurse-covid-statistics/nurse-covid-statistics.component.html
  src/app/components/nurse/covid/nurse-covid-statistics/nurse-covid-statistics.component.ts
Labels: size/XXL
