Repository RAF-SI-2022/Bolnica-1-Frontend, pull requests merged in 2023-03, with the labels that each got.

#34 Admin search employee and profile
  package-lock.json
  package-lock_BACKUP_1657.json
  package-lock_BACKUP_1959.json
  package-lock_BASE_1657.json
  package-lock_BASE_1959.json
  package-lock_LOCAL_1657.json
  package-lock_LOCAL_1959.json
  package-lock_REMOTE_1657.json
  package-lock_REMOTE_1959.json
  package.json
  src/app/app.module.ts
  src/app/app/app.component.ts
  src/app/components/admin/admin-search-employee/admin-search-employee.component.html
  src/app/components/admin/admin-search-employee/admin-search-employee.component.spec.ts
  src/app/components/admin/admin-search-employee/admin-search-employee.component.ts
  src/app/components/general/profile/profile.component.html
  src/app/components/general/profile/profile.component.ts
  src/app/models/models.ts
  src/app/services/user-service/user.service.ts
  src/index.html
  src/styles.css
Labels: size/XXL

#35 validacija
  src/app/components/admin/admin-add-employee/admin-add-employee.component.html
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.html
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.ts
  src/app/components/general/login/login.component.html
Labels: size/L

#36 Update klasa
  src/app/app/app.component.ts
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.html
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.ts
  src/app/components/admin/admin-search-employee/admin-search-employee.component.html
  src/app/components/admin/admin-search-employee/admin-search-employee.component.ts
  src/app/components/general/login/login.component.html
  src/app/components/general/login/login.component.ts
  src/app/components/general/profile/profile.component.html
  src/app/components/general/profile/profile.component.ts
  src/app/components/general/reset-password-link/reset-password-link.component.html
  src/app/services/user-service/user.service.ts
  src/styles.css
Labels: size/XL

#37 Sredjena paginacija. Odradjen search zaposlenih od strane admina sa f…
  src/app/components/admin/admin-search-employee/admin-search-employee.component.html
  src/app/components/admin/admin-search-employee/admin-search-employee.component.ts
  src/app/models/models.ts
  src/app/services/receptionist-servise/receptionist.service.ts
  src/app/services/user-service/user.service.ts
Labels: size/L

#38 Sredjene stranice admin-add-employe i admin-edit-employee
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/components/admin/admin-add-employee/admin-add-employee.component.html
  src/app/components/admin/admin-add-employee/admin-add-employee.component.ts
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.html
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.ts
  src/app/components/admin/admin-search-employee/admin-search-employee.component.html
  src/app/components/admin/admin-search-employee/admin-search-employee.component.ts
  src/app/components/general/login/login.component.ts
  src/app/components/general/profile/profile.component.html
  src/app/components/general/profile/profile.component.ts
  src/app/models/models.ts
  src/app/services/receptionist-servise/receptionist.service.ts
  src/app/services/user-service/user.service.ts
Labels: size/XL

#40 Popravljeni modeli, metode, i edit zaposljenog od strane admina.
  src/app/components/admin/admin-add-employee/admin-add-employee.component.ts
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.html
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.ts
  src/app/components/admin/admin-search-employee/admin-search-employee.component.ts
  src/app/components/general/profile/profile.component.html
  src/app/components/general/profile/profile.component.ts
  src/app/models/models.ts
  src/app/services/user-service/user.service.ts
Labels: size/L

#41 Zaboravila sam checkbox. Dodat je.
  src/app/components/admin/admin-search-employee/admin-search-employee.component.html
Labels: size/XS

#43 profil
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.html
  src/app/components/general/profile/profile.component.html
  src/app/components/general/profile/profile.component.ts
  src/app/models/models.ts
  src/app/services/user-service/user.service.ts
Labels: size/L

#44 Doradjen addEmployee
  package-lock.json
  src/app/components/admin/admin-add-employee/admin-add-employee.component.ts
  src/app/models/models.ts
  src/app/services/user-service/user.service.ts
Labels: size/XXL

#64 [View] [LS] Radni prostor #24
  package-lock.json
  package.json
  src/app/app/app.component.html
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.css
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.html
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
Labels: size/L

#67 [View][MS/VMS] Pocetna strana #29 i #24
  src/app/app/app.component.html
  src/app/components/biochemist/biochemist-search/biochemist-search.component.css
  src/app/components/biochemist/biochemist-search/biochemist-search.component.html
  src/app/components/biochemist/biochemist-search/biochemist-search.component.spec.ts
  src/app/components/biochemist/biochemist-search/biochemist-search.component.ts
  src/app/components/biochemist/biochemist-workspace/biochemist-workspace.component.css
  src/app/components/biochemist/biochemist-workspace/biochemist-workspace.component.html
  src/app/components/biochemist/biochemist-workspace/biochemist-workspace.component.ts
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.css
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.html
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
  src/app/components/nurse/nurse-workspace/nurse-workspace.component.css
  src/app/components/nurse/nurse-workspace/nurse-workspace.component.html
Labels: size/XL

#71 doradjeni nurse search/add/edit i doctor search
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.html
  src/app/components/nurse/nurse-add-patient/nurse-add-patient.component.html
  src/app/components/nurse/nurse-edit-patient/nurse-edit-patient.component.html
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.html
Labels: size/XL

#70 [View] [LS] Radni prostor za rad sa pacijentom #25
  src/app/app/app.component.html
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.css
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.html
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.ts
Labels: size/L

#73 Promenjene role, username i odradjen deo za sprint-2
  src/app/app.module.ts
  src/app/app/app.component.ts
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.spec.ts
  src/app/components/admin/admin-search-employee/admin-search-employee.component.spec.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.ts
  src/app/components/general/login/login.component.ts
  src/app/components/general/profile/profile.component.ts
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.spec.ts
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.ts
  src/app/components/nurse/nurse-workspace/nurse-workspace.component.css
  src/app/components/nurse/nurse-workspace/nurse-workspace.component.html
  src/app/components/nurse/nurse-workspace/nurse-workspace.component.ts
  src/app/services/patient-service/patient.service.ts
  src/app/services/user-service/user.service.ts
Labels: size/L

#74 [View] [MS/VMS] Zakazivanje pregleda #66
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/app/app.component.html
  src/app/components/nurse/nurse-schedule-appointment/nurse-schedule-appointment.component.html
  src/app/components/nurse/nurse-schedule-appointment/nurse-schedule-appointment.component.ts
Labels: size/XL

#75 Sredjen profil, pretraga pacijenata i krenuta doctor-medical-chart ko…
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app/app.component.ts
  src/app/components/admin/admin-add-employee/admin-add-employee.component.ts
  src/app/components/admin/admin-search-employee/admin-search-employee.component.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.html
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.ts
  src/app/components/general/profile/profile.component.html
  src/app/components/general/profile/profile.component.ts
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.html
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.ts
  src/app/models/patient/PatientUpdate.ts
  src/app/services/patient-service/patient.service.ts
  src/app/services/user-service/user.service.ts
Labels: size/L

#76 Nurse add, nurse edit, doctor workspace one
  src/app/components/admin/admin-edit-employee/admin-edit-employee.component.ts
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.html
  src/app/components/doctor/doctor-workspace-one-patient/doctor-workspace-one-patient.component.ts
  src/app/components/nurse/nurse-add-patient/nurse-add-patient.component.html
  src/app/components/nurse/nurse-add-patient/nurse-add-patient.component.ts
  src/app/components/nurse/nurse-edit-patient/nurse-edit-patient.component.html
  src/app/components/nurse/nurse-edit-patient/nurse-edit-patient.component.ts
  src/app/models/patient/Anamnesis.ts
  src/app/models/patient/Patient.ts
  src/app/models/patient/PatientCreate.ts
  src/app/models/patient/PatientGeneral.ts
  src/app/models/patient/PatientGeneralDto.ts
  src/app/models/patient/PatientUpdate.ts
  src/app/services/patient-service/patient.service.ts
  src/app/services/user-service/user.service.ts
Labels: size/XL

#77 Sredjen doctor-medical-chart i prilagodjeni modeli
  src/app/app-routing.module.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/models/patient/Allergy.ts
  src/app/models/patient/GeneralMedicalData.ts
  src/app/models/patient/GeneralMedicalDataCreate.ts
  src/app/models/patient/Vaccination.ts
  src/app/services/patient-service/patient.service.ts
Labels: size/L

#78 [View] [MS/VMS] Zakazivanje pregleda #66 doradjen
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/nurse/nurse-schedule-appointment/nurse-schedule-appointment.component.html
  src/app/components/nurse/nurse-schedule-appointment/nurse-schedule-appointment.component.ts
  src/main.ts
  src/styles.css
Labels: size/L

#79 Sredjen drop-down i vakcine u doctor-medical-chart
  src/app/components/admin/admin-add-employee/admin-add-employee.component.html
  src/app/components/admin/admin-search-employee/admin-search-employee.component.html
  src/app/components/admin/admin-search-employee/admin-search-employee.component.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.css
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.html
  src/app/components/doctor/doctor-search-patients/doctor-search-patients.component.ts
  src/app/components/nurse/nurse-add-patient/nurse-add-patient.component.html
  src/app/components/nurse/nurse-add-patient/nurse-add-patient.component.ts
  src/app/components/nurse/nurse-edit-patient/nurse-edit-patient.component.html
  src/app/components/nurse/nurse-edit-patient/nurse-edit-patient.component.ts
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.html
  src/app/components/nurse/nurse-search-patients/nurse-search-patients.component.ts
  src/app/models/patient/Allergy.ts
  src/app/services/patient-service/patient.service.ts
  src/app/services/user-service/user.service.ts
Labels: size/L

#80 Dodat technician-issuing-results html
  src/app/components/technician/technician-issuing-results-details/technician-issuing-results-details.component.html
  src/app/components/technician/technician-issuing-results/technician-issuing-results.component.html
Labels: size/L

#81 [View] [LS] Radni prostor za kreiranje uputa #58
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.css
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.html
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
Labels: size/L

#82 Dodat technician-patinet-admission
  src/app/components/technician/technician-patient-admission/technician-patient-admission.component.html
Labels: size/L
