Repository RAF-SI-2022/Bolnica-1-Frontend, pull requests merged in 2023-07, with the labels that each got.

#252 Kovid - izmene
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/app/app.component.html
  src/app/components/doctor/covid/doctor-covid-create-referral/doctor-covid-create-referral.component.html
  src/app/components/doctor/covid/doctor-covid-create-referral/doctor-covid-create-referral.component.ts
  src/app/components/doctor/covid/doctor-covid-exam/doctor-covid-exam.component.html
  src/app/components/doctor/covid/doctor-covid-exam/doctor-covid-exam.component.ts
  src/app/components/doctor/covid/doctor-covid-statistics/doctor-covid-statistics.component.html
  src/app/components/doctor/covid/doctor-covid-statistics/doctor-covid-statistics.component.ts
  src/app/components/doctor/covid/doctor-covid-stats-details/doctor-covid-stats-details.component.css
  src/app/components/doctor/covid/doctor-covid-stats-details/doctor-covid-stats-details.component.html
  src/app/components/doctor/covid/doctor-covid-stats-details/doctor-covid-stats-details.component.spec.ts
  src/app/components/doctor/covid/doctor-covid-stats-details/doctor-covid-stats-details.component.ts
  src/app/components/doctor/doctor-create-referral/doctor-create-referral.component.ts
  src/app/components/doctor/doctor-infirmary-create-referral/doctor-infirmary-create-referral.component.ts
  src/app/components/doctor/doctor-infirmary-medical-chart/doctor-infirmary-medical-chart.component.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.html
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/doctor/doctor-workspace/doctor-workspace.component.ts
  src/app/components/nurse/covid/nurse-covid-certificate/nurse-covid-certificate.component.css
  src/app/components/nurse/covid/nurse-covid-certificate/nurse-covid-certificate.component.html
  src/app/components/nurse/covid/nurse-covid-certificate/nurse-covid-certificate.component.spec.ts
  src/app/components/nurse/covid/nurse-covid-certificate/nurse-covid-certificate.component.ts
  src/app/components/nurse/covid/nurse-covid-statistics/nurse-covid-statistics.component.html
  src/app/components/nurse/covid/nurse-covid-statistics/nurse-covid-statistics.component.ts
  src/app/components/nurse/covid/nurse-covid-stats-details/nurse-covid-stats-details.component.css
  src/app/components/nurse/covid/nurse-covid-stats-details/nurse-covid-stats-details.component.html
  src/app/components/nurse/covid/nurse-covid-stats-details/nurse-covid-stats-details.component.spec.ts
  src/app/components/nurse/covid/nurse-covid-stats-details/nurse-covid-stats-details.component.ts
  src/app/components/nurse/nurse-vaccine-covid/nurse-vaccine-covid.component.css
  src/app/components/nurse/nurse-vaccine-covid/nurse-vaccine-covid.component.html
  src/app/components/nurse/nurse-vaccine-covid/nurse-vaccine-covid.component.spec.ts
  src/app/components/nurse/nurse-vaccine-covid/nurse-vaccine-covid.component.ts
  src/app/components/nurse/nurse-vaccine-regular/nurse-vaccine-regular.component.css
  src/app/components/nurse/nurse-vaccine-regular/nurse-vaccine-regular.component.html
  src/app/components/nurse/nurse-vaccine-regular/nurse-vaccine-regular.component.spec.ts
  src/app/components/nurse/nurse-vaccine-regular/nurse-vaccine-regular.component.ts
  src/app/components/nurse/vaccination/nurse-daily-vaccination/nurse-daily-vaccination.component.css
  src/app/components/nurse/vaccination/nurse-daily-vaccination/nurse-daily-vaccination.component.html
  src/app/components/nurse/vaccination/nurse-daily-vaccination/nurse-daily-vaccination.component.spec.ts
  src/app/components/nurse/vaccination/nurse-daily-vaccination/nurse-daily-vaccination.component.ts
  src/app/components/nurse/vaccination/nurse-schedule-vaccination/nurse-schedule-vaccination.component.css
  src/app/components/nurse/vaccination/nurse-schedule-vaccination/nurse-schedule-vaccination.component.html
  src/app/components/nurse/vaccination/nurse-schedule-vaccination/nurse-schedule-vaccination.component.spec.ts
  src/app/components/nurse/vaccination/nurse-schedule-vaccination/nurse-schedule-vaccination.component.ts
  src/app/components/nurse/vaccination/nurse-vaccination-admission/nurse-vaccination-admission.component.css
  src/app/components/nurse/vaccination/nurse-vaccination-admission/nurse-vaccination-admission.component.html
  src/app/components/nurse/vaccination/nurse-vaccination-admission/nurse-vaccination-admission.component.spec.ts
  src/app/components/nurse/vaccination/nurse-vaccination-admission/nurse-vaccination-admission.component.ts
  src/app/models/covid-enums/CovidStat.ts
  src/app/models/covid/CovidExaminationHistoryDto.ts
  src/app/models/covid/CovidStatsResultDto.ts
  src/app/models/covid/CovidSummed.ts
  src/app/models/vaccination/ScheduledVaccinationCreateDto.ts
  src/app/models/vaccination/ScheduledVaccinationDto
  src/app/models/vaccination/ScheduledVaccinationDto.ts
  src/app/services/laboratory-service/laboratory.service.ts
  src/app/services/patient-service/patient.service.ts
  src/app/services/user-service/user.service.ts
Labels: size/XXL

#255 Promene kovid
  src/app/app.module.ts
  src/app/app/app.component.html
  src/app/components/biochemist/biochemist-details-analysis/biochemist-details-analysis.component.html
  src/app/components/biochemist/biochemist-details-analysis/biochemist-details-analysis.component.ts
  src/app/components/doctor/covid/doctor-covid-create-referral/doctor-covid-create-referral.component.ts
  src/app/components/doctor/covid/doctor-covid-statistics/doctor-covid-statistics.component.html
  src/app/components/doctor/covid/doctor-covid-statistics/doctor-covid-statistics.component.ts
  src/app/components/doctor/covid/doctor-covid-stats-details/doctor-covid-stats-details.component.css
  src/app/components/doctor/covid/doctor-covid-stats-details/doctor-covid-stats-details.component.html
  src/app/components/doctor/covid/doctor-covid-stats-details/doctor-covid-stats-details.component.ts
  src/app/components/doctor/doctor-infirmary-medical-chart/doctor-infirmary-medical-chart.component.ts
  src/app/components/doctor/doctor-medical-chart/doctor-medical-chart.component.ts
  src/app/components/doctor/shifts/doctor-my-shifts/doctor-my-shifts.component.css
  src/app/components/doctor/shifts/doctor-my-shifts/doctor-my-shifts.component.html
  src/app/components/doctor/shifts/doctor-my-shifts/doctor-my-shifts.component.spec.ts
  src/app/components/doctor/shifts/doctor-my-shifts/doctor-my-shifts.component.ts
  src/app/components/doctor/shifts/doctor-schedule-shifts/doctor-schedule-shifts.component.css
  src/app/components/doctor/shifts/doctor-schedule-shifts/doctor-schedule-shifts.component.html
  src/app/components/doctor/shifts/doctor-schedule-shifts/doctor-schedule-shifts.component.spec.ts
  src/app/components/doctor/shifts/doctor-schedule-shifts/doctor-schedule-shifts.component.ts
  src/app/components/nurse/covid/nurse-covid-statistics/nurse-covid-statistics.component.html
  src/app/components/nurse/covid/nurse-covid-statistics/nurse-covid-statistics.component.ts
  src/app/components/nurse/covid/nurse-covid-stats-details/nurse-covid-stats-details.component.css
  src/app/components/nurse/covid/nurse-covid-stats-details/nurse-covid-stats-details.component.html
  src/app/components/nurse/covid/nurse-covid-stats-details/nurse-covid-stats-details.component.ts
  src/app/components/nurse/vaccination/nurse-daily-vaccination/nurse-daily-vaccination.component.html
  src/app/components/nurse/vaccination/nurse-daily-vaccination/nurse-daily-vaccination.component.ts
  src/app/components/nurse/vaccination/nurse-vaccination-admission/nurse-vaccination-admission.component.html
  src/app/components/nurse/vaccination/nurse-vaccination-admission/nurse-vaccination-admission.component.ts
  src/app/models/laboratory/LabAnalysisDto.ts
  src/app/models/shifts/AllShiftsDto.ts
  src/app/models/shifts/EmployeeShiftDto.ts
  src/app/models/shifts/ShiftCreateDto.ts
  src/app/models/shifts/ShiftDto.ts
  src/app/models/shifts/ShiftScheduleCreateDto.ts
  src/app/models/shifts/ShiftScheduleDto.ts
  src/app/services/infirmary-service/infirmary.service.ts
  src/app/services/patient-service/patient.service.ts
  src/app/services/user-service/user.service.ts
Labels: size/XXL

#259 srejdeni dugmici popup
  src/app/components/nurse/vaccination/nurse-schedule-vaccination/nurse-schedule-vaccination.component.ts
Labels: size/S

#261 Testovi
  cypress/e2e/covidNew.cy.ts
  cypress/e2e/covidNew1.cy.ts
  cypress/e2e/covidNew2.cy.ts
  cypress/e2e/covidNew3.cy.ts
  cypress/e2e/covidNew4.cy.ts
  cypress/e2e/covidNew5.cy.ts
  cypress/e2e/covidNew6.cy.ts
  src/app/components/doctor/covid/doctor-covid-create-referral/doctor-covid-create-referral.component.html
  src/app/components/doctor/shifts/doctor-schedule-shifts/doctor-schedule-shifts.component.html
  src/app/components/nurse/covid/nurse-covid-certificate/nurse-covid-certificate.component.html
  src/app/components/nurse/covid/nurse-covid-statistics/nurse-covid-statistics.component.html
  src/app/components/nurse/nurse-infirmary-patient-admission/nurse-infirmary-patient-admission.component.html
  src/app/components/nurse/nurse-infirmary-patient-admission/nurse-infirmary-patient-admission.component.ts
  src/app/components/nurse/nurse-infirmary-scheduled-patients/nurse-infirmary-scheduled-patients.component.html
  src/app/components/nurse/nurse-infirmary-workspace-one/nurse-infirmary-workspace-one.component.html
  src/app/components/nurse/nurse-schedule-appointment/nurse-schedule-appointment.component.html
  src/app/components/nurse/vaccination/nurse-daily-vaccination/nurse-daily-vaccination.component.html
  src/app/components/nurse/vaccination/nurse-schedule-vaccination/nurse-schedule-vaccination.component.html
  src/app/components/nurse/vaccination/nurse-vaccination-admission/nurse-vaccination-admission.component.html
Labels: size/L
